[package]
name = "revvy02/mocknetwork"
description = "Library designed to replicate roblox networking behavior"
version = "1.3.0"
license = "MIT"
authors = ["revvy02"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

exclude = ["**"]
include = ["src", "src/**", "wally.toml", "default.project.json", "LICENSE"]

[dependencies]
TestEZ = "roblox/testez@0.4.1"
TrueSignal = "revvy02/truesignal@1.0.2"