[package]
name = "revvy02/slick"
description = "Luau state management and signal library"
version = "0.0.9"
license = "MIT"
authors = ["revvy02"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

exclude = ["**"]
include = ["src", "src/**", "wally.toml", "default.project.json", "LICENSE"]

[dependencies]
Cleaner = "revvy02/cleaner@1.0.0"
TestEZ = "roblox/testez@0.4.1"
Promise = "evaera/promise@4.0.0"